; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

?501c_t		struc ;	(sizeof=0x1)
arg1b:		.db ?
?501c_t		ends

; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

?5042_t		struc ;	(sizeof=0x4)
arg1w:		.dw ?
arg2w:		.dw ?
?5042_t		ends

; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

?50c1_t		struc ;	(sizeof=0x2)
arg1w:		.dw ?
?50c1_t		ends

; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

?5206_t		struc ;	(sizeof=0x4)
arg1b:		.db ?
arg2w:		.dw ?
arg3b:		.db ?
?5206_t		ends

; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

; enum ISIS
$OPEN:		 = 0
$CLOSE:		 = 1
$DELETE:	 = 2
$READ:		 = 3
$WRITE:		 = 4
$SEEK:		 = 5
$LOAD:		 = 6
$RENAME:	 = 7
$CONSOL:	 = 8
$EXIT:		 = 9
$ATTRIB:	 = 10
$RESCAN:	 = 11
$ERROR:		 = 12
$WHOCON:	 = 13
$SPATH:		 = 14

;
; ЙННННННННННННННННННННННННННННННННННННННННННННННННННННННННННННННННННННННННН»
; є	This file is generated by The Interactive Disassembler (IDA)	    є
; є	Copyright (c) 2003 by DataRescue sa/nv,	<ida@datarescue.com>	    є
; є  Licensed to: Michael Wolski - Personal Use	(1-user	Standard 07/2003)   є
; ИНННННННННННННННННННННННННННННННННННННННННННННННННННННННННННННННННННННННННј
;
; File Name   :	E:\sandbox\Intel80\itools\link_2.1\link.ovl.bin
; Format      :	Binary File
; Base Address:	0000h Range: 5000h - 5D94h Loaded length: 0D94h

; Processor	  : 8085 []
; Target assembler: Table Driven Assembler (TASM) by Speech Technology Inc.

; ННННННННННННННННННННННННННННННННННННННННННННННННННННННННННННННННННННННННННН

; Segment type:	Pure code
		.org 3680h
		.block 35h
ZERO:		.block 567h
GABORT:		.block 1Dh		; CODE XREF: sub_501C+10p
					; PUTRECORD+22p
REPORTERROR:	.block 0C3h
WARN:		.block 45h
WARNCR:		.block 20h
FATALINPUTERROR:.block 18h		; CODE XREF: sub_5589+2Dp
					; sub_5589+1BFp ...
ILLFMT:		.block 0Fh		; CODE XREF: sub_5589+12Ap
					; sub_5589+2AFp
ISISRETURNTEST:	.block 22h
SAFEREAD:	.block 35h
SAFEWRITE:	.block 30h		; CODE XREF: sub_50D7+68p sub_5589+3Ep ...
FATALOPEN:	.block 46h		; CODE XREF: PASS2+18p
FATALCLOSE:	.block 24h		; CODE XREF: PASS2+189p PASS2+1BAp
SAFESEEK:	.block 35h		; CODE XREF: PASS2+9Bp
FATALDELETE:	.block 35h
GETHIGH:	.block 32h		; CODE XREF: sub_5B46+Ap sub_5B46+16p
GETLOW:		.block 32h
OPENNEXTINPUTELEMENT:.block 1Ch		; CODE XREF: PASS2+55p
READINPUT:	.block 20h		; CODE XREF: sub_5589+91p
READRECORD:	.block 74h		; CODE XREF: sub_545A+35p sub_545A+89p ...
VERIFYCHKSUM:	.block 20h		; CODE XREF: sub_5535+4Dp sub_5AEA+55p
SKIPRECORD:	.block 2Eh		; CODE XREF: PASS2+17Bp
READHEADER:	.block 33h		; CODE XREF: sub_544B+Bp sub_545A+D7p	...
ASCERTAIN:	.block 17h
READNAME:	.block 2Dh		; CODE XREF: sub_544B+3p sub_545A+ABp	...
SKIPMODULE:	.block 12h
POSITION:	.block 32h
PUSHRECORD:	.block 3Bh
POPRECORD:	.block 3Bh
SWAPRECORD:	.block 73h
INPUTTYPEINFO:	.block 0Dh		; CODE XREF: sub_545A+B4p sub_5535+11p
LENGTHTYPEINFO:	.block 0Ah		; CODE XREF: sub_52AA+61p sub_53A3+35p
COMPARETYPEINFO:.block 18h
TRANSFERTYPEINFO:.block	15h
PUTTYPEINFO:	.block 11h		; CODE XREF: sub_545A+B9p
HASHF:		.block 40h
LOOKUP:		.block 0DDh		; CODE XREF: sub_5535+23p sub_5AEA+26p
PUTEDICT:	.block 7Fh		; CODE XREF: sub_5535+40p
GETEDICT:	.block 5Ah		; CODE XREF: sub_53A3+25p
					; sub_5589+2B7p
INITSEGCOMB:	.block 47h		; CODE XREF: PASS2+27p
INIT:		.block 48h
UPDATESEGCOMB:	.block 27Ch
P12MODHDR:	.block 122h		; CODE XREF: PASS2+10Fp
CLOSE:		.block 13h
DELETE:		.block 13h
ERROR:		.block 15h
EXIT:		.block 0Fh
LOAD:		.block 24h
MEMCK:		.block 6
OPEN:		.block 24h
READ:		.block 24h
SEEK:		.block 24h
WRITE:		.block 1Fh
DEBLANK:	.block 1Dh
DELIMIT:	.block 51h
FILEERROR:	.block 8Ah		; CODE XREF: sub_5535+34p sub_5AEA+37p ...
NUMOUT:		.block 9Ah
SCANBLANK:	.block 3Ah
@P0014:		.block 1		; CODE XREF: sub_52AA+74p
@P0015:		.block 3
@P0016:		.block 1
@P0017:		.block 8
@P0018:		.block 3
@P0019:		.block 7
@P0029:		.block 2		; CODE XREF: sub_5589+431p
@P0030:		.block 1Dh
@P0094:		.block 3		; CODE XREF: sub_5589+440p
@P0095:		.block 7		; CODE XREF: PUTRECORD+16p
					; PUTRECORD+1Cp ...
@P0098:		.block 2		; CODE XREF: PUTRECORD+32p
					; PUTRECORD+45p ...
@P0099:		.block 3		; CODE XREF: sub_5589+1B2p
@P0100:		.block 8		; CODE XREF: sub_50D7+6p
@P0101:		.block 3		; CODE XREF: sub_501C+9p sub_5149+7Ep	...
@P0102:		.block 8		; CODE XREF: sub_5589+6Fp
@P0103:		.block 3		; CODE XREF: sub_5149+2Ep sub_52AA+19p ...
@P0104:		.block 61h		; CODE XREF: sub_53A3+1Ap sub_5589+1Dp ...
COMMANDTAIL:	.block 1
		.block 1
OUTFILE:	.block 2		; DATA XREF: sub_50D7+56r sub_5589+30r ...
OUTFILEPTR:	.block 2		; DATA XREF: PASS2+Ar
MAPWANTED:	.block 1
MAPFILE:	.block 1
		.block 1
MAPFILEPTR:	.block 1
		.block 1
INFILE:		.block 2		; DATA XREF: PASS2+81r	PASS2+181r
INFILEPTR:	.block 2		; DATA XREF: sub_5535+2Dr sub_5AEA+30r ...
OUTMODULENAMELENGTH:.block 1		; DATA XREF: sub_5149+5o sub_544Bo ...
OUTMODULENAME:	.block 20h
NEEDANCESTORNAME:.block	1		; DATA XREF: sub_544B+6o sub_545Ar ...
OUTTRANID:	.block 1		; DATA XREF: sub_5149+Bo
OUTTRANVN:	.block 1
INITTRANIDVN:	.block 1
MODENDMODTYP:	.block 1		; DATA XREF: PASS2+19Eo
MODENDSEGID:	.block 1
MODENDOFFSET:	.block 2
FILELIST:	.block 2		; DATA XREF: PASS2+2Dr
FILELISTEND:	.block 2
CONTIGPTR:	.block 2
CONTIGEND:	.block 6
MODULELISTBASE:	.block 2		; DATA XREF: PASS2+68w	PASS2+6Br ...
MODULELISTEND:	.block 2
CURRENTLENGTH:	.block 0Ah		; DATA XREF: sub_5149+27o sub_5149+3Eo
CURRENTRELTYP:	.block 5		; DATA XREF: sub_5149+49o
CURRENTOFFSET:	.block 0Ah		; DATA XREF: sub_545A+6Co
					; sub_5589+24Fo ...
GAPPTR:		.block 3
LASTGAP:	.block 2
CENTRYBASE:	.block 2		; DATA XREF: sub_5149+76w sub_5149+7Bo ...
COMMONTHREAD:	.block 2		; DATA XREF: sub_5149+73r sub_522F+2o	...
LASTCOMMON:	.block 2
BLANKRELTYP:	.block 1		; DATA XREF: sub_5149+5Cr sub_5149+6Cr
BLANKLENGTH:	.block 2		; DATA XREF: sub_5149+67r
NOCOMMON:	.block 1		; DATA XREF: sub_5B46r
HASHTAB:	.block 100h		; DATA XREF: sub_52AA+22o
SENTRYBASE:	.block 2		; DATA XREF: sub_52AA+27w sub_52AA+2Ar ...
NEXTS:		.block 2		; DATA XREF: sub_53A3+2o sub_53A3+12r	...
EDICT:		.block 100h
NEWEXTERNALS:	.block 1
EDICTFILE:	.block 0Dh
EXTERNALSONDISK:.block 1
EDICTAFTN:	.block 2
TEMPNAME:	.block 21h		; DATA XREF: sub_545A+A8o sub_545A+AEo ...
PUBLICSMODE:	.block 1		; DATA XREF: PASS2+60w
STATUS:		.block 2		; DATA XREF: sub_50D7+65o sub_5589+38o ...
ACTUAL:		.block 2
OVERLAYFILENAME:.block 4Dh
MEMBOT:		.block 2		; DATA XREF: PASS2+3w
		.block 7
TP:		.block 1		; DATA XREF: sub_545A+1Ar sub_545A+22o ...
RECLEN:		.block 2		; DATA XREF: sub_5589+1Ao sub_5589+52r ...
REMAINDER:	.block 2		; DATA XREF: sub_545A+7Ao sub_5535+2o	...
RECORDBLOCK0:	.block 2
RECORDBYTE0:	.block 110h
aC19761977Intel:.text "(C) 1976, 1977 INTEL CORP "
		.db 22h
		.text "$"

; ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ S U B	R O U T	I N E ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ


sub_501C:				; CODE XREF: sub_5149+2p sub_522F+49p	...
		lxi	h, ?sub_501C	; sub_501C(arg1b)
		mov	m, c		; --end	prologue
		mvi	a, 0
		lxi	d, word_5D92
		call	@P0101
		ora	l
		jz	loc_502F
		call	GABORT

loc_502F:				; CODE XREF: sub_501C+Dj
		lda	?sub_501C.arg1b
		sta	byte_5D96
		lxi	h, 3
		shld	word_5D92
		lxi	h, byte_5D99
		shld	word_5D94
		ret
; End of function sub_501C


; ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ S U B	R O U T	I N E ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ


PUTRECORD:				; CODE XREF: sub_50C1+12p sub_5149+11p ...
		lxi	h, (?PUTRECORD.arg2w+1)	; PUTRECORD(arg1w, arg2w)
		mov	m, d
		dcx	h
		mov	m, e
		dcx	h
		mov	m, b
		dcx	h
		mov	m, c		; --end	prologue
		lhld	word_5D94
		xchg
		lhld	?PUTRECORD.arg1w
		dad	d
		xchg
		lxi	h, byte_5D96
		call	@P0095
		lxi	d, 403h
		call	@P0095
		jnc	loc_5067
		call	GABORT

loc_5067:				; CODE XREF: PUTRECORD+1Fj
		lhld	?PUTRECORD.arg1w
		dcx	h
		shld	word_6DA9
		lxi	b, ?PUTRECORD.arg2w
		lxi	d, word_5D94
		call	@P0098
		ora	l
		jz	loc_50AE
		lxi	h, 0
		shld	word_6DA7

loc_5081:				; CODE XREF: PUTRECORD+69j
		lxi	d, word_6DA9
		lxi	b, word_6DA7
		call	@P0098
		jc	loc_50AE
		lhld	word_6DA7
		xchg
		lhld	?PUTRECORD.arg2w
		dad	d
		push	h
		lhld	word_6DA7
		xchg
		lhld	word_5D94
		dad	d
		pop	b
		ldax	b
		mov	m, a
		lxi	d, 1
		lhld	word_6DA7
		dad	d
		shld	word_6DA7
		jnc	loc_5081

loc_50AE:				; CODE XREF: PUTRECORD+36j
					; PUTRECORD+48j
		lhld	?PUTRECORD.arg1w
		xchg
		lhld	word_5D94
		dad	d
		shld	word_5D94
		lhld	word_5D92
		dad	d
		shld	word_5D92
		ret
; End of function PUTRECORD


; ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ S U B	R O U T	I N E ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ


sub_50C1:				; CODE XREF: sub_5149+8p sub_522F+63p	...
		lxi	h, (?sub_50C1.arg1w+1) ; sub_50C1(arg1w)
		mov	m, b
		dcx	h
		mov	m, c		; --end	prologue
		lhld	?sub_50C1.arg1w
		mov	a, m
		inr	a
		lhld	?sub_50C1.arg1w
		xchg
		mov	c, a
		mvi	b, 0
		call	PUTRECORD
		ret
; End of function sub_50C1


; ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ S U B	R O U T	I N E ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ


sub_50D7:				; CODE XREF: sub_5149+B9p sub_522F+38p ...
		lxi	b, byte_5D96
		lxi	d, word_5D94
		call	@P0100
		dcx	h
		dcx	h
		shld	word_6DAD
		mov	a, l
		mov	h, b
		mov	l, c
		inx	h
		mov	m, a
		lhld	word_6DAD
		mov	a, h
		sta	byte_5D98
		inx	h
		shld	word_6DAD
		xchg
		dcx	h
		mov	c, m
		inx	h
		mov	b, m
		mov	h, b
		mov	l, c
		mvi	m, 0
		lxi	h, 0
		shld	word_6DAF

loc_5104:				; CODE XREF: sub_50D7+53j
		lxi	d, word_6DAD
		lxi	b, word_6DAF
		call	@P0098
		jc	loc_512D
		lhld	word_5D94
		push	h
		lhld	word_6DAF
		lxi	b, byte_5D96
		dad	b
		pop	d
		ldax	d
		sub	m
		xchg
		mov	m, a
		lxi	d, 1
		lhld	word_6DAF
		dad	d
		shld	word_6DAF
		jnc	loc_5104

loc_512D:				; CODE XREF: sub_50D7+36j
		lhld	OUTFILE
		push	h
		lxi	b, byte_5D96
		push	b
		lhld	word_6DAD
		inx	h
		inx	h
		mov	b, h
		mov	c, l
		lxi	d, STATUS
		call	SAFEWRITE
		lxi	h, 0
		shld	word_5D92
		ret
; End of function sub_50D7


; ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ S U B	R O U T	I N E ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ


sub_5149:				; CODE XREF: PASS2+1Bp
		mvi	c, 2
		call	sub_501C
		lxi	b, OUTMODULENAMELENGTH
		call	sub_50C1
		lxi	d, OUTTRANID
		lxi	b, 2
		call	PUTRECORD
		lxi	h, byte_6DB5
		mvi	m, 1

loc_5162:				; CODE XREF: sub_5149+59j
		mvi	a, 4
		lxi	h, byte_6DB5
		cmp	m
		jc	loc_51A5
		lhld	byte_6DB5
		mvi	h, 0
		lxi	b, CURRENTLENGTH
		dad	h
		dad	b
		mvi	a, 0
		call	@P0103
		ora	l
		jz	loc_519E
		lhld	byte_6DB5
		push	h
		lhld	byte_6DB5
		mvi	h, 0
		lxi	b, CURRENTLENGTH
		dad	h
		dad	b
		push	h
		lhld	byte_6DB5
		mvi	h, 0
		lxi	b, CURRENTRELTYP
		dad	b
		mov	e, m
		pop	h
		mov	c, m
		inx	h
		mov	b, m
		call	sub_5206

loc_519E:				; CODE XREF: sub_5149+32j
		lxi	h, byte_6DB5
		inr	m
		jnz	loc_5162

loc_51A5:				; CODE XREF: sub_5149+1Fj
		lda	BLANKRELTYP
		cpi	0
		jz	loc_51BC
		mvi	c, 0FFh
		push	b
		lhld	BLANKLENGTH
		mov	b, h
		mov	c, l
		lhld	BLANKRELTYP
		xchg
		call	sub_5206

loc_51BC:				; CODE XREF: sub_5149+61j
		lhld	COMMONTHREAD
		shld	CENTRYBASE

loc_51C2:				; CODE XREF: sub_5149+B6j
		mvi	a, 0
		lxi	d, CENTRYBASE
		call	@P0101
		ora	l
		jz	loc_5202
		lxi	b, 3
		lhld	CENTRYBASE
		dad	b
		mov	c, m
		push	b
		lxi	b, 4
		lhld	CENTRYBASE
		dad	b
		push	h
		lhld	CENTRYBASE
		inx	h
		inx	h
		mvi	a, 0Eh
		ana	m
		ora	a
		rar
		pop	h
		mov	c, m
		inx	h
		mov	b, m
		mov	e, a
		call	sub_5206
		lxi	b, 6
		lhld	CENTRYBASE
		dad	b
		mov	e, m
		inx	h
		mov	d, m
		xchg
		shld	CENTRYBASE
		jmp	loc_51C2
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5202:				; CODE XREF: sub_5149+82j
		call	sub_50D7
		ret
; End of function sub_5149


; ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ S U B	R O U T	I N E ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ


sub_5206:				; CODE XREF: sub_5149+52p sub_5149+70p ...
		lxi	h, ?sub_5206.arg3b ; sub_5206(arg1b, arg2w, arg3b)
		mov	m, e
		dcx	h
		mov	m, b
		dcx	h
		mov	m, c
		dcx	h
		pop	d
		pop	b
		mov	m, c
		push	d		; --end	prologue
		lxi	d, ?sub_5206
		lxi	b, 1
		call	PUTRECORD
		lxi	d, ?sub_5206.arg2w
		lxi	b, 2
		call	PUTRECORD
		lxi	d, ?sub_5206.arg3b
		lxi	b, 1
		call	PUTRECORD
		ret
; End of function sub_5206


; ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ S U B	R O U T	I N E ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ


sub_522F:				; CODE XREF: PASS2+1Ep
		mvi	a, 0
		lxi	d, COMMONTHREAD
		call	@P0101
		ora	l
		jnz	loc_523C
		ret
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_523C:				; CODE XREF: sub_522F+9j
		lhld	COMMONTHREAD
		shld	CENTRYBASE

loc_5242:				; CODE XREF: sub_522F+74j
		mvi	a, 0
		lxi	d, CENTRYBASE
		call	@P0101
		ora	l
		jz	loc_52A6
		lxi	b, 8
		lhld	CENTRYBASE
		dad	b
		mov	e, m
		mvi	d, 0
		lhld	word_5D92
		dad	d
		inx	h
		inx	h
		lxi	d, 403h
		call	@P0095
		jnc	loc_526A
		call	sub_50D7

loc_526A:				; CODE XREF: sub_522F+35j
		mvi	a, 0
		lxi	d, word_5D92
		call	@P0101
		ora	l
		jnz	loc_527B
		mvi	c, 2Eh
		call	sub_501C

loc_527B:				; CODE XREF: sub_522F+44j
		lxi	b, 3
		lhld	CENTRYBASE
		dad	b
		xchg
		lxi	b, 1
		call	PUTRECORD
		lxi	b, 8
		lhld	CENTRYBASE
		dad	b
		mov	b, h
		mov	c, l
		call	sub_50C1
		lxi	b, 6
		lhld	CENTRYBASE
		dad	b
		mov	e, m
		inx	h
		mov	d, m
		xchg
		shld	CENTRYBASE
		jmp	loc_5242
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_52A6:				; CODE XREF: sub_522F+1Cj
		call	sub_50D7
		ret
; End of function sub_522F


; ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ S U B	R O U T	I N E ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ


sub_52AA:				; CODE XREF: PASS2+21p
		lxi	h, byte_6DB6	; sub_52AA()
		mvi	m, 0

loc_52AF:				; CODE XREF: sub_52AA+F5j
		mvi	a, 4
		lxi	h, byte_6DB6
		cmp	m
		jc	locret_53A2
		lxi	h, 0
		shld	word_6DB7

loc_52BE:				; CODE XREF: sub_52AA+DFj
		mvi	a, 7Fh
		lxi	h, word_6DB7
		call	@P0103
		jc	loc_538C
		lhld	word_6DB7
		lxi	b, HASHTAB
		dad	h
		dad	b
		shld	SENTRYBASE

loc_52D4:				; CODE XREF: sub_52AA+D2j
		lhld	SENTRYBASE
		mvi	a, 0
		call	@P0103
		ora	l
		jz	loc_537F
		lhld	SENTRYBASE
		mov	e, m
		inx	h
		mov	d, m
		xchg
		shld	SENTRYBASE
		inx	h
		inx	h
		lxi	b, 3
		push	h
		lhld	SENTRYBASE
		dad	b
		lda	byte_6DB6
		sub	m
		sui	1
		sbb	a
		pop	h
		ana	m
		rar
		jnc	loc_537C
		lxi	b, 6
		lhld	SENTRYBASE
		dad	b
		mov	c, m
		inx	h
		mov	b, m
		call	LENGTHTYPEINFO
		shld	word_6DBB
		lxi	b, 8
		lhld	SENTRYBASE
		dad	b
		mov	a, m
		adi	3
		lxi	d, word_6DBB
		call	@P0014
		shld	word_6DB9
		push	h
		lhld	word_5D92
		pop	b
		dad	b
		lxi	d, 403h
		call	@P0095
		jnc	loc_5336
		call	sub_50D7

loc_5336:				; CODE XREF: sub_52AA+86j
		mvi	a, 0
		lxi	d, word_5D92
		call	@P0101
		ora	l
		jnz	loc_5350
		mvi	c, 16h
		call	sub_501C
		lxi	d, byte_6DB6
		lxi	b, 1
		call	PUTRECORD

loc_5350:				; CODE XREF: sub_52AA+95j
		lxi	b, 4
		lhld	SENTRYBASE
		dad	b
		xchg
		lxi	b, 2
		call	PUTRECORD
		lxi	b, 8
		lhld	SENTRYBASE
		dad	b
		mov	b, h
		mov	c, l
		call	sub_50C1
		lxi	b, 6
		lhld	SENTRYBASE
		dad	b
		mov	e, m
		inx	h
		mov	d, m
		lhld	word_6DBB
		mov	b, h
		mov	c, l
		call	PUTRECORD

loc_537C:				; CODE XREF: sub_52AA+54j
		jmp	loc_52D4
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_537F:				; CODE XREF: sub_52AA+33j
		lxi	d, 1
		lhld	word_6DB7
		dad	d
		shld	word_6DB7
		jnc	loc_52BE

loc_538C:				; CODE XREF: sub_52AA+1Cj
		mvi	a, 0
		lxi	d, word_5D92
		call	@P0101
		ora	l
		jz	loc_539B
		call	sub_50D7

loc_539B:				; CODE XREF: sub_52AA+EBj
		lxi	h, byte_6DB6
		inr	m
		jnz	loc_52AF

locret_53A2:				; CODE XREF: sub_52AA+Bj
		ret
; End of function sub_52AA


; ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ S U B	R O U T	I N E ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ


sub_53A3:				; CODE XREF: PASS2+24p
		mvi	a, 0
		lxi	d, NEXTS
		call	@P0101
		ora	l
		jz	locret_544A
		lxi	h, 0
		shld	word_6DBD

loc_53B5:				; CODE XREF: sub_53A3+A1j
		lhld	NEXTS
		dcx	h
		xchg
		lxi	h, word_6DBD
		call	@P0104
		jc	loc_5447
		lhld	word_6DBD
		mov	b, h
		mov	c, l
		call	GETEDICT
		shld	SENTRYBASE
		lxi	b, 6
		lhld	SENTRYBASE
		dad	b
		mov	c, m
		inx	h
		mov	b, m
		call	LENGTHTYPEINFO
		shld	word_6DBF
		lhld	word_6DBF
		inx	h
		lxi	b, 8
		push	h
		lhld	SENTRYBASE
		dad	b
		mov	e, m
		mvi	d, 0
		pop	h
		dad	d
		shld	word_6DC1
		xchg
		lhld	word_5D92
		dad	d
		lxi	d, 403h
		call	@P0095
		jnc	loc_5403
		call	sub_50D7

loc_5403:				; CODE XREF: sub_53A3+5Aj
		mvi	a, 0
		lxi	d, word_5D92
		call	@P0101
		ora	l
		jnz	loc_5414
		mvi	c, 18h
		call	sub_501C

loc_5414:				; CODE XREF: sub_53A3+69j
		lxi	b, 8
		lhld	SENTRYBASE
		dad	b
		mov	a, m
		inr	a
		lhld	SENTRYBASE
		dad	b
		xchg
		mov	c, a
		mvi	b, 0
		call	PUTRECORD
		lxi	b, 6
		lhld	SENTRYBASE
		dad	b
		mov	e, m
		inx	h
		mov	d, m
		lhld	word_6DBF
		mov	b, h
		mov	c, l
		call	PUTRECORD
		lxi	d, 1
		lhld	word_6DBD
		dad	d
		shld	word_6DBD
		jnc	loc_53B5

loc_5447:				; CODE XREF: sub_53A3+1Dj
		call	sub_50D7

locret_544A:				; CODE XREF: sub_53A3+9j
		ret
; End of function sub_53A3


; ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ S U B	R O U T	I N E ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ


sub_544B:				; CODE XREF: PASS2+140p
		lxi	b, OUTMODULENAMELENGTH
		call	READNAME
		lxi	h, NEEDANCESTORNAME
		mvi	m, 0FFh
		call	READHEADER
		ret
; End of function sub_544B


; ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ S U B	R O U T	I N E ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ


sub_545A:				; CODE XREF: PASS2+11Ep PASS2+146p ...
		lda	NEEDANCESTORNAME
		rar
		jnc	loc_5474
		mvi	c, 10h
		call	sub_501C
		lxi	b, OUTMODULENAMELENGTH
		call	sub_50C1
		call	sub_50D7
		lxi	h, NEEDANCESTORNAME
		mvi	m, 0

loc_5474:				; CODE XREF: sub_545A+4j
		lda	TP
		cpi	14h
		jnz	loc_5489
		lxi	h, TP
		mvi	m, 8
		lxi	h, byte_6DC3
		mvi	m, 1
		jmp	loc_5492
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5489:				; CODE XREF: sub_545A+1Fj
		lxi	d, byte_6DC3
		lxi	b, 1
		call	READRECORD

loc_5492:				; CODE XREF: sub_545A+2Cj
		lhld	TP
		mov	c, l
		call	sub_501C
		lhld	byte_6DC3
		mvi	h, 0
		xchg
		lhld	word_6DA0
		dad	d
		mov	a, m
		sta	byte_6DC3
		lxi	d, byte_6DC3
		lxi	b, 1
		call	PUTRECORD
		lda	byte_6DC3
		cpi	6
		jc	loc_54C1
		lxi	h, 0
		shld	word_6DC6
		jmp	loc_54D2
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_54C1:				; CODE XREF: sub_545A+5Bj
		lhld	byte_6DC3
		mvi	h, 0
		lxi	b, CURRENTOFFSET
		dad	h
		dad	b
		mov	e, m
		inx	h
		mov	d, m
		xchg
		shld	word_6DC6

loc_54D2:				; CODE XREF: sub_545A+64j sub_545A+D1j
		mvi	a, 1
		lxi	h, REMAINDER
		call	@P0103
		jnc	loc_552E
		lxi	d, word_6DC4
		lxi	b, 2
		call	READRECORD
		lhld	word_6DC6
		xchg
		lhld	word_6DC4
		dad	d
		shld	word_6DC4
		lxi	d, word_6DC4
		lxi	b, 2
		call	PUTRECORD
		lda	TP
		cpi	12h
		jnz	loc_5519
		lxi	b, TEMPNAME
		call	READNAME
		lxi	b, TEMPNAME
		call	sub_50C1
		call	INPUTTYPEINFO
		mov	b, h
		mov	c, l
		call	PUTTYPEINFO
		jmp	loc_552B
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5519:				; CODE XREF: sub_545A+A5j
		lxi	d, word_6DC4
		lxi	b, 2
		call	READRECORD
		lxi	d, word_6DC4
		lxi	b, 2
		call	PUTRECORD

loc_552B:				; CODE XREF: sub_545A+BCj
		jmp	loc_54D2
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_552E:				; CODE XREF: sub_545A+80j
		call	sub_50D7
		call	READHEADER
		ret
; End of function sub_545A


; ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ S U B	R O U T	I N E ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ


sub_5535:				; CODE XREF: sub_5535+4Aj PASS2+158p
		mvi	a, 1
		lxi	h, REMAINDER
		call	@P0103
		jnc	loc_5582
		lxi	b, TEMPNAME
		call	READNAME
		call	INPUTTYPEINFO
		shld	word_6DC8
		lxi	b, TEMPNAME
		push	b
		lxi	b, word_6DC8
		push	b
		mvi	e, 0
		mvi	c, 0FFh
		call	LOOKUP
		rar
		jc	loc_556C
		mvi	c, 0DBh
		push	b
		lhld	INFILEPTR
		mov	b, h
		mov	c, l
		mvi	e, 0FFh
		call	FILEERROR

loc_556C:				; CODE XREF: sub_5535+27j
		lhld	word_6DC8
		mov	b, h
		mov	c, l
		lhld	NEXTS
		xchg
		call	PUTEDICT
		lhld	NEXTS
		inx	h
		shld	NEXTS
		jmp	sub_5535
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5582:				; CODE XREF: sub_5535+8j
		call	VERIFYCHKSUM
		call	READHEADER
		ret
; End of function sub_5535


; ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ S U B	R O U T	I N E ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ


sub_5589:				; CODE XREF: PASS2+118p
		lxi	d, byte_6DCA
		lxi	b, 3
		call	READRECORD
		lhld	byte_6DCA
		mvi	h, 0
		xchg
		lhld	word_6DA0
		dad	d
		mov	a, m
		sta	byte_6DCA
		lxi	d, 401h
		lxi	h, RECLEN
		call	@P0104
		jnc	loc_563F
		lda	byte_6DCA
		cpi	0
		jz	loc_55B9
		mvi	c, 0D3h
		call	FATALINPUTERROR

loc_55B9:				; CODE XREF: sub_5589+28j
		lhld	OUTFILE
		push	h
		lxi	b, TP
		push	b
		lxi	d, STATUS
		lxi	b, 3
		call	SAFEWRITE
		lhld	OUTFILE
		push	h
		lxi	b, byte_6DCA
		push	b
		lxi	d, STATUS
		lxi	b, 3
		call	SAFEWRITE
		lhld	RECLEN
		dcx	h
		dcx	h
		dcx	h
		shld	RECLEN

loc_55E4:				; CODE XREF: sub_5589+A7j
		mvi	a, 0
		lxi	h, RECLEN
		call	@P0103
		jnc	loc_5633
		lxi	h, 7D0h
		shld	word_6DD3
		lxi	d, RECLEN
		call	@P0102
		jnc	loc_5604
		lhld	RECLEN
		shld	word_6DD3

loc_5604:				; CODE XREF: sub_5589+72j
		lxi	b, word_6DD3
		lxi	d, RECLEN
		call	@P0098
		xchg
		dcx	h
		mov	m, e
		inx	h
		mov	m, d
		lhld	word_6DD3
		mov	b, h
		mov	c, l
		lxi	d, byte_659E
		call	READINPUT
		lhld	OUTFILE
		push	h
		lxi	b, byte_659E
		push	b
		lhld	word_6DD3
		mov	b, h
		mov	c, l
		lxi	d, STATUS
		call	SAFEWRITE
		jmp	loc_55E4
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5633:				; CODE XREF: sub_5589+63j
		lxi	h, 0
		shld	REMAINDER
		call	READHEADER
		jmp	locret_5AE9
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_563F:				; CODE XREF: sub_5589+20j
		lhld	REMAINDER
		dcx	h
		shld	word_6DD5
		lhld	word_6DD5
		mov	b, h
		mov	c, l
		lxi	d, byte_5D9C
		call	READRECORD
		lxi	h, 0
		shld	word_6DCD

loc_5657:				; CODE XREF: sub_5589+EDj
		lxi	d, word_6DD5
		lxi	b, word_6DCD
		call	@P0098
		jc	loc_5679
		lhld	word_6DCD
		lxi	b, byte_619D
		dad	b
		mvi	m, 0
		lxi	d, 1
		lhld	word_6DCD
		dad	d
		shld	word_6DCD
		jnc	loc_5657

loc_5679:				; CODE XREF: sub_5589+D7j
		lhld	word_6DD5
		lxi	b, byte_619D
		dad	b
		mvi	m, 0FFh
		lhld	word_6DCB
		shld	word_6DD9
		push	h
		lhld	word_6DD5
		pop	b
		dad	b
		dcx	h
		shld	word_6DDB
		call	READHEADER

loc_5695:				; CODE XREF: sub_5589+39Fj
		lda	TP
		sui	20h
		sbb	a
		cma
		push	psw
		mvi	a, 24h
		lxi	h, TP
		sub	m
		sbb	a
		cma
		pop	b
		mov	c, b
		ana	c
		rar
		jnc	loc_592B
		lda	TP
		rar
		jnc	loc_56B6
		call	ILLFMT

loc_56B6:				; CODE XREF: sub_5589+127j
		lda	TP
		sui	20h
		ora	a
		rar
		sta	byte_6DE1
		cpi	2
		jnz	loc_56DF
		lxi	d, byte_6DE2
		lxi	b, 1
		call	READRECORD
		lhld	byte_6DE2
		mvi	h, 0
		xchg
		lhld	word_6DA0
		dad	d
		mov	a, m
		sta	byte_6DE2
		jmp	loc_56E5
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_56DF:				; CODE XREF: sub_5589+139j
		lda	byte_6DCA
		sta	byte_6DE2

loc_56E5:				; CODE XREF: sub_5589+153j
		lxi	d, byte_6DE0
		lxi	b, 1
		call	READRECORD
		lhld	byte_6DE1
		mvi	h, 0
		lxi	d, 3
		call	@P0034
		push	h
		lhld	byte_6DE0
		mvi	h, 0
		pop	b
		dad	b
		xchg
		lxi	h, byte_6DDF
		mov	m, e

loc_5706:				; CODE XREF: sub_5589+399j
		mvi	a, 1
		lxi	h, REMAINDER
		call	@P0103
		jnc	loc_5925
		lda	byte_6DE1
		cpi	0
		jnz	loc_5722
		lxi	d, word_6DD7
		lxi	b, 2
		call	READRECORD

loc_5722:				; CODE XREF: sub_5589+18Dj
		lxi	d, word_6DCB
		lxi	b, 2
		call	READRECORD
		lxi	b, word_6DD9
		lxi	d, word_6DCB
		call	@P0098
		sbb	a
		xchg
		lxi	d, word_6DDB
		dcx	h
		push	psw
		call	@P0099
		sbb	a
		pop	b
		mov	c, b
		ora	c
		rar
		jnc	loc_574B
		mvi	c, 0DFh
		call	FATALINPUTERROR

loc_574B:				; CODE XREF: sub_5589+1BAj
		lxi	b, word_6DD9
		lxi	d, word_6DCB
		call	@P0098
		shld	word_6DDD
		lxi	b, byte_619D
		dad	b
		mov	a, m
		sui	0
		adi	0FFh
		sbb	a
		lhld	word_6DDD
		inx	b
		dad	b
		push	psw
		mov	a, m
		sui	0
		adi	0FFh
		sbb	a
		push	psw
		lda	byte_6DE0
		sui	3
		sui	1
		sbb	a
		pop	b
		mov	c, b
		ana	c
		pop	b
		mov	c, b
		ora	c
		rar
		jnc	loc_5785
		mvi	c, 0DFh
		call	FATALINPUTERROR

loc_5785:				; CODE XREF: sub_5589+1F4j
		lda	byte_6DE0
		cpi	3
		jnz	loc_5796
		lhld	word_6DDD
		lxi	b, byte_619E
		dad	b
		mvi	m, 0FFh

loc_5796:				; CODE XREF: sub_5589+201j
		lhld	word_6DDD
		lxi	b, byte_5D9C
		dad	b
		shld	word_6DE3
		lda	byte_6DE1
		cpi	0
		jz	loc_582C
		lhld	word_6DDD
		lxi	b, byte_619D
		dad	b
		lda	byte_6DDF
		mov	m, a
		lhld	word_6DDD
		lxi	b, byte_659E
		dad	h
		dad	b
		lda	byte_6DE2
		mov	m, a
		inx	h
		mvi	m, 0
		lda	byte_6DE2
		cpi	6
		jc	loc_57D3
		lxi	h, 0
		shld	word_6DD7
		jmp	loc_57E4
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_57D3:				; CODE XREF: sub_5589+23Ej
		lhld	byte_6DE2
		mvi	h, 0
		lxi	b, CURRENTOFFSET
		dad	h
		dad	b
		mov	e, m
		inx	h
		mov	d, m
		xchg
		shld	word_6DD7

loc_57E4:				; CODE XREF: sub_5589+247j
		lda	byte_6DE0
		dcr	a
		mov	c, a
		mvi	b, 0
		lxi	h, off_5823
		dad	b
		dad	b
		mov	e, m
		inx	h
		mov	d, m
		xchg
		pchl
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_57F5:				; DATA XREF: sub_5589+29Ao
		lhld	word_6DE3
		push	h
		lhld	word_6DD7
		mov	a, l
		pop	h
		add	m
		mov	m, a
		jmp	loc_5829
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5803:				; DATA XREF: sub_5589+29Co
		lhld	word_6DE3
		push	h
		lhld	word_6DD7
		mov	a, h
		pop	h
		add	m
		mov	m, a
		jmp	loc_5829
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5811:				; DATA XREF: sub_5589+29Eo
		lhld	word_6DE3
		lxi	d, word_6DD7
		push	h
		call	@P0012
		xchg
		pop	h
		mov	m, e
		inx	h
		mov	m, d
		jmp	loc_5829
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД
off_5823:	.dw loc_57F5		; DATA XREF: sub_5589+262o
		.dw loc_5803
		.dw loc_5811
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5829:				; CODE XREF: sub_5589+277j
					; sub_5589+285j ...
		jmp	loc_5922
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_582C:				; CODE XREF: sub_5589+21Cj
		lxi	b, NEXTS
		lxi	d, word_6DD7
		call	@P0098
		jc	loc_583B
		call	ILLFMT

loc_583B:				; CODE XREF: sub_5589+2ACj
		lhld	word_6DD7
		mov	b, h
		mov	c, l
		call	GETEDICT
		shld	SENTRYBASE
		lhld	SENTRYBASE
		inx	h
		inx	h
		mov	a, m
		rar
		jnc	loc_58FF
		lda	byte_6DE0
		dcr	a
		mov	c, a
		mvi	b, 0
		lxi	h, off_589C
		dad	b
		dad	b
		mov	e, m
		inx	h
		mov	d, m
		xchg
		pchl
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5861:				; DATA XREF: sub_5589+313o
		lhld	word_6DE3
		lxi	b, 4
		push	h
		lhld	SENTRYBASE
		dad	b
		mov	a, m
		pop	h
		add	m
		mov	m, a
		jmp	loc_58A2
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5873:				; DATA XREF: sub_5589+315o
		lhld	word_6DE3
		lxi	b, 5
		push	h
		lhld	SENTRYBASE
		dad	b
		mov	a, m
		pop	h
		add	m
		mov	m, a
		jmp	loc_58A2
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5885:				; DATA XREF: sub_5589+317o
		lhld	word_6DE3
		lxi	b, 4
		push	h
		lhld	SENTRYBASE
		dad	b
		pop	d
		call	@P0012
		xchg
		dcx	h
		mov	m, e
		inx	h
		mov	m, d
		jmp	loc_58A2
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД
off_589C:	.dw loc_5861		; DATA XREF: sub_5589+2CEo
		.dw loc_5873
		.dw loc_5885
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_58A2:				; CODE XREF: sub_5589+2E7j
					; sub_5589+2F9j ...
		lxi	b, 3
		lhld	SENTRYBASE
		dad	b
		mov	a, m
		cpi	0
		jnz	loc_58BB
		lhld	word_6DDD
		lxi	b, byte_619D
		dad	b
		mvi	m, 0FFh
		jmp	loc_58FC
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_58BB:				; CODE XREF: sub_5589+323j
		lxi	b, 3
		lhld	SENTRYBASE
		dad	b
		lda	byte_6DCA
		cmp	m
		jnz	loc_58D9
		lda	byte_6DE0
		adi	3
		lhld	word_6DDD
		lxi	b, byte_619D
		dad	b
		mov	m, a
		jmp	loc_58E6
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_58D9:				; CODE XREF: sub_5589+33Dj
		lda	byte_6DE0
		adi	6
		lhld	word_6DDD
		lxi	b, byte_619D
		dad	b
		mov	m, a

loc_58E6:				; CODE XREF: sub_5589+34Dj
		lxi	b, 3
		lhld	SENTRYBASE
		dad	b
		push	h
		lhld	word_6DDD
		lxi	b, byte_659E
		dad	h
		dad	b
		pop	d
		ldax	d
		mov	m, a
		inx	h
		mvi	m, 0

loc_58FC:				; CODE XREF: sub_5589+32Fj
		jmp	loc_5922
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_58FF:				; CODE XREF: sub_5589+2C4j
		lhld	word_6DDD
		lxi	b, byte_619D
		dad	b
		lda	byte_6DDF
		mov	m, a
		lxi	b, 4
		lhld	SENTRYBASE
		dad	b
		push	h
		lhld	word_6DDD
		lxi	b, byte_659E
		dad	h
		dad	b
		xthl
		mov	c, m
		inx	h
		mov	b, m
		pop	h
		mov	m, c
		inx	h
		mov	m, b

loc_5922:				; CODE XREF: sub_5589+2A0j
					; sub_5589+373j
		jmp	loc_5706
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5925:				; CODE XREF: sub_5589+185j
		call	READHEADER
		jmp	loc_5695
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_592B:				; CODE XREF: sub_5589+120j
		mvi	c, 6
		call	sub_501C
		lda	byte_6DCA
		cpi	6
		jc	loc_5941
		lhld	word_6DD9
		shld	word_6DCB
		jmp	loc_5954
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5941:				; CODE XREF: sub_5589+3ACj
		lhld	byte_6DCA
		mvi	h, 0
		lxi	b, CURRENTOFFSET
		dad	h
		dad	b
		lxi	d, word_6DD9
		call	@P0012
		shld	word_6DCB

loc_5954:				; CODE XREF: sub_5589+3B5j
		lxi	d, byte_6DCA
		lxi	b, 3
		call	PUTRECORD
		lhld	word_6DD5
		mov	b, h
		mov	c, l
		lxi	d, byte_5D9C
		call	PUTRECORD
		call	sub_50D7
		lxi	h, 0
		shld	word_6DCD

loc_5971:				; CODE XREF: sub_5589+410j
		lxi	b, word_6DD5
		lxi	d, word_6DCD
		call	@P0098
		sbb	a
		lxi	b, byte_619D
		dcx	d
		push	psw
		call	@P0013
		mov	a, m
		inr	a
		mov	c, a
		mvi	a, 1
		sub	c
		sbb	a
		cma
		pop	b
		mov	c, b
		ana	c
		rar
		jnc	loc_599C
		lhld	word_6DCD
		inx	h
		shld	word_6DCD
		jmp	loc_5971
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_599C:				; CODE XREF: sub_5589+406j
					; sub_5589+55Dj
		lxi	b, word_6DD5
		lxi	d, word_6DCD
		call	@P0098
		jnc	locret_5AE9
		lhld	word_6DCD
		lxi	b, byte_619D
		dad	b
		mov	a, m
		sta	byte_6DDF
		dcr	a
		mov	e, a
		mvi	d, 0
		lxi	h, 3
		call	@P0029
		lxi	h, byte_6DE1
		mov	m, e
		mvi	d, 0
		call	@P0035
		lda	byte_6DDF
		call	@P0094
		xchg
		lxi	h, byte_6DE0
		mov	m, e
		lhld	word_6DCD
		lxi	b, byte_659E
		dad	h
		dad	b
		mov	l, m
		mov	a, l
		sta	byte_6DE2
		lhld	word_6DD5
		shld	word_6DCF
		lhld	word_6DCD
		shld	word_6DD1

loc_59EA:				; CODE XREF: sub_5589+551j
		lhld	word_6DD5
		dcx	h
		xchg
		lxi	h, word_6DD1
		call	@P0104
		jc	loc_5ADD
		lhld	word_6DD1
		lxi	b, byte_619D
		dad	b
		lda	byte_6DDF
		sub	m
		sui	1
		sbb	a
		push	psw
		lda	byte_6DE1
		sui	2
		adi	0FFh
		sbb	a
		lhld	word_6DD1
		lxi	b, byte_659E
		dad	h
		dad	b
		mov	l, m
		push	psw
		lda	byte_6DE2
		sub	l
		sui	1
		sbb	a
		pop	b
		mov	c, b
		ora	c
		pop	b
		mov	c, b
		ana	c
		rar
		jnc	loc_5AA7
		lxi	d, 5
		lhld	word_5D92
		dad	d
		lxi	d, 401h
		call	@P0095
		jnc	loc_5A3D
		call	sub_50D7

loc_5A3D:				; CODE XREF: sub_5589+4AEj
		mvi	a, 0
		lxi	d, word_5D92
		call	@P0101
		ora	l
		jnz	loc_5A70
		lhld	byte_6DE1
		mvi	h, 0
		lxi	b, (aC19761977Intel+19h)
		dad	b
		mov	c, m
		call	sub_501C
		lda	byte_6DE1
		cpi	2
		jnz	loc_5A67
		lxi	d, byte_6DE2
		lxi	b, 1
		call	PUTRECORD

loc_5A67:				; CODE XREF: sub_5589+4D2j
		lxi	d, byte_6DE0
		lxi	b, 1
		call	PUTRECORD

loc_5A70:				; CODE XREF: sub_5589+4BDj
		lda	byte_6DE1
		cpi	0
		jnz	loc_5A87
		lhld	word_6DD1
		lxi	b, byte_659E
		dad	h
		dad	b
		xchg
		lxi	b, 2
		call	PUTRECORD

loc_5A87:				; CODE XREF: sub_5589+4ECj
		lhld	word_6DCB
		xchg
		lhld	word_6DD1
		dad	d
		shld	word_6DDD
		lxi	d, word_6DDD
		lxi	b, 2
		call	PUTRECORD
		lhld	word_6DD1
		lxi	b, byte_619D
		dad	b
		mvi	m, 0FFh
		jmp	loc_5AD0
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5AA7:				; CODE XREF: sub_5589+49Ej
		lhld	word_6DD1
		lxi	b, byte_619D
		dad	b
		mov	a, m
		inr	a
		mov	c, a
		mvi	a, 1
		sub	c
		sbb	a
		lxi	b, word_6DD5
		lxi	d, word_6DCF
		push	psw
		call	@P0098
		ora	l
		sui	1
		sbb	a
		pop	b
		mov	c, b
		ana	c
		rar
		jnc	loc_5AD0
		lhld	word_6DD1
		shld	word_6DCF

loc_5AD0:				; CODE XREF: sub_5589+51Bj
					; sub_5589+53Ej
		lxi	d, 1
		lhld	word_6DD1
		dad	d
		shld	word_6DD1
		jnc	loc_59EA

loc_5ADD:				; CODE XREF: sub_5589+46Cj
		lhld	word_6DCF
		shld	word_6DCD
		call	sub_50D7
		jmp	loc_599C
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

locret_5AE9:				; CODE XREF: sub_5589+B3j
					; sub_5589+41Cj
		ret
; End of function sub_5589


; ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ S U B	R O U T	I N E ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ


sub_5AEA:				; CODE XREF: sub_5AEA+52j PASS2+E0p
		mvi	a, 1
		lxi	h, REMAINDER
		call	@P0103
		jnc	loc_5B3F
		lxi	d, byte_6DE5
		lxi	b, 1
		call	READRECORD
		lxi	b, TEMPNAME
		call	READNAME
		lxi	b, TEMPNAME
		push	b
		lxi	b, word_6DE6
		push	b
		mvi	e, 0
		mvi	c, 0
		call	LOOKUP
		rar
		jc	loc_5B24
		mvi	c, 0DBh
		push	b
		lhld	INFILEPTR
		mov	b, h
		mov	c, l
		mvi	e, 0FFh
		call	FILEERROR

loc_5B24:				; CODE XREF: sub_5AEA+2Aj
		lhld	word_6DE6
		shld	CENTRYBASE
		lxi	b, 3
		dad	b
		push	h
		lhld	byte_6DE5
		mvi	h, 0
		xchg
		lhld	word_6DA0
		dad	d
		pop	d
		ldax	d
		mov	m, a
		jmp	sub_5AEA
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5B3F:				; CODE XREF: sub_5AEA+8j
		call	VERIFYCHKSUM
		call	READHEADER
		ret
; End of function sub_5AEA


; ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ S U B	R O U T	I N E ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ


sub_5B46:				; CODE XREF: PASS2+2Ap
		lda	NOCOMMON
		rar
		jnc	loc_5B59
		lxi	b, 5
		call	GETHIGH
		shld	word_6DA0
		jmp	loc_5B6B
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5B59:				; CODE XREF: sub_5B46+4j
		lxi	b, 100h
		call	GETHIGH
		shld	word_6DA0
		lxi	b, 0FFh
		lhld	word_6DA0
		dad	b
		mvi	m, 0FFh

loc_5B6B:				; CODE XREF: sub_5B46+10j
		lxi	h, byte_6DE8
		mvi	m, 0

loc_5B70:				; CODE XREF: sub_5B46+45j
		mvi	a, 4
		lxi	h, byte_6DE8
		cmp	m
		jc	locret_5B8E
		lhld	byte_6DE8
		mvi	h, 0
		xchg
		lhld	word_6DA0
		dad	d
		lda	byte_6DE8
		mov	m, a
		lxi	h, byte_6DE8
		inr	m
		jnz	loc_5B70

locret_5B8E:				; CODE XREF: sub_5B46+30j
		ret
; End of function sub_5B46


; ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ S U B	R O U T	I N E ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ


PASS2:
		lxi	h, byte_6DED	; PASS2()
		shld	MEMBOT
		lxi	b, OUTFILE
		push	b
		lhld	OUTFILEPTR
		push	h
		lxi	b, 2
		push	b
		lxi	d, STATUS
		lxi	b, 0
		call	FATALOPEN
		call	sub_5149
		call	sub_522F
		call	sub_52AA
		call	sub_53A3
		call	INITSEGCOMB
		call	sub_5B46
		lhld	FILELIST
		shld	word_6DE9

loc_5BC2:				; CODE XREF: PASS2+196j
		mvi	a, 0
		lxi	d, word_6DE9
		call	@P0101
		ora	l
		jz	loc_5D28
		lxi	b, 4
		lhld	word_6DE9
		dad	b
		mov	a, m
		rar
		jc	loc_5D1B
		lxi	b, 5
		lhld	word_6DE9
		dad	b
		shld	INFILEPTR
		call	OPENNEXTINPUTELEMENT
		lxi	b, 4
		lhld	word_6DE9
		dad	b
		mov	a, m
		sta	PUBLICSMODE
		lhld	word_6DE9
		inx	h
		inx	h
		shld	MODULELISTBASE

loc_5BFA:				; CODE XREF: PASS2+17Ej
		lhld	MODULELISTBASE
		mvi	a, 0
		call	@P0103
		ora	l
		jz	loc_5D10
		lhld	MODULELISTBASE
		mov	e, m
		inx	h
		mov	d, m
		xchg
		shld	MODULELISTBASE
		lhld	INFILE
		push	h
		lxi	b, 2
		push	b
		lhld	MODULELISTBASE
		inx	h
		inx	h
		push	h
		lhld	MODULELISTBASE
		lxi	d, 4
		dad	d
		mov	b, h
		mov	c, l
		lxi	d, STATUS
		call	SAFESEEK
		call	READHEADER
		lda	TP
		cpi	2
		jz	loc_5C3D
		mvi	c, 0DBh
		call	FATALINPUTERROR

loc_5C3D:				; CODE XREF: PASS2+A6j
		lxi	h, 0
		shld	NEXTS

loc_5C43:				; CODE XREF: PASS2+178j
		lda	TP
		cpi	4
		jz	loc_5D0A
		lda	TP
		sui	20h
		sbb	a
		cma
		push	psw
		mvi	a, 24h
		lxi	h, TP
		sub	m
		sbb	a
		cma
		pop	b
		mov	c, b
		ana	c
		rar
		jnc	loc_5C67
		mvi	c, 0E0h
		call	FATALINPUTERROR

loc_5C67:				; CODE XREF: PASS2+D0j
		lda	TP
		cpi	2Eh
		jnz	loc_5C75
		call	sub_5AEA
		jmp	loc_5D07
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5C75:				; CODE XREF: PASS2+DDj
		mvi	a, 18h
		lxi	h, TP
		sub	m
		sbb	a
		ora	m
		rar
		jnc	loc_5C84
		call	sub_5D4D

loc_5C84:				; CODE XREF: PASS2+EFj
		lda	TP
		ora	a
		rar
		mov	c, a
		mvi	b, 0
		lxi	h, off_5CED
		dad	b
		dad	b
		mov	e, m
		inx	h
		mov	d, m
		xchg
		pchl
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5C96:				; DATA XREF: PASS2+15Eo
		call	sub_5D4D
		jmp	loc_5D07
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5C9C:				; DATA XREF: PASS2+160o
		mvi	c, 0FFh
		call	P12MODHDR
		jmp	loc_5D07
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5CA4:				; DATA XREF: PASS2+162o
		jmp	loc_5D07
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5CA7:				; DATA XREF: PASS2+164o
		call	sub_5589
		jmp	loc_5D07
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5CAD:				; DATA XREF: PASS2+166o
		call	sub_545A
		jmp	loc_5D07
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5CB3:				; DATA XREF: PASS2+168o
		call	sub_5D4D
		jmp	loc_5D07
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5CB9:				; DATA XREF: PASS2+16Ao
		call	sub_5D4D
		jmp	loc_5D07
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5CBF:				; DATA XREF: PASS2+16Co
		mvi	c, 0CCh
		push	b
		lhld	INFILEPTR
		mov	b, h
		mov	c, l
		mvi	e, 0FFh
		call	FILEERROR
		jmp	loc_5D07
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5CCF:				; DATA XREF: PASS2+16Eo
		call	sub_544B
		jmp	loc_5D07
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5CD5:				; DATA XREF: PASS2+170o
		call	sub_545A
		jmp	loc_5D07
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5CDB:				; DATA XREF: PASS2+172o
		call	sub_545A
		jmp	loc_5D07
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5CE1:				; DATA XREF: PASS2+174o
		call	READHEADER
		jmp	loc_5D07
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5CE7:				; DATA XREF: PASS2+176o
		call	sub_5535
		jmp	loc_5D07
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД
off_5CED:	.dw loc_5C96		; DATA XREF: PASS2+FDo
		.dw loc_5C9C
		.dw loc_5CA4
		.dw loc_5CA7
		.dw loc_5CAD
		.dw loc_5CB3
		.dw loc_5CB9
		.dw loc_5CBF
		.dw loc_5CCF
		.dw loc_5CD5
		.dw loc_5CDB
		.dw loc_5CE1
		.dw loc_5CE7
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5D07:				; CODE XREF: PASS2+E3j	PASS2+10Aj ...
		jmp	loc_5C43
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5D0A:				; CODE XREF: PASS2+B9j
		call	SKIPRECORD
		jmp	loc_5BFA
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5D10:				; CODE XREF: PASS2+74j
		lhld	INFILE
		mov	b, h
		mov	c, l
		lxi	d, STATUS
		call	FATALCLOSE

loc_5D1B:				; CODE XREF: PASS2+48j
		lhld	word_6DE9
		mov	e, m
		inx	h
		mov	d, m
		xchg
		shld	word_6DE9
		jmp	loc_5BC2
; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

loc_5D28:				; CODE XREF: PASS2+3Cj
		mvi	c, 4
		call	sub_501C
		lxi	d, MODENDMODTYP
		lxi	b, 4
		call	PUTRECORD
		call	sub_50D7
		mvi	c, 0Eh
		call	sub_501C
		call	sub_50D7
		lhld	OUTFILE
		mov	b, h
		mov	c, l
		lxi	d, STATUS
		call	FATALCLOSE
		ret
; End of function PASS2


; ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ S U B	R O U T	I N E ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ


sub_5D4D:				; CODE XREF: PASS2+F2p	PASS2+107p ...
		mvi	c, 0D1h
		push	b
		lhld	INFILEPTR
		mov	b, h
		mov	c, l
		mvi	e, 0FFh
		call	FILEERROR
		ret
; End of function sub_5D4D

; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

@P0011:
		mov	l, c
		mov	h, b

; ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ S U B	R O U T	I N E ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ


@P0012:					; CODE XREF: sub_5589+28Fp
					; sub_5589+308p ...
		mov	c, m
		inx	h
		mov	b, m
; End of function @P0012


; ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ S U B	R O U T	I N E ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ


@P0013:					; CODE XREF: sub_5589+3F7p
		ldax	d
		add	c
		mov	l, a
		inx	d
		ldax	d
		adc	b
		mov	h, a
		ret
; End of function @P0013


; ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ S U B	R O U T	I N E ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ


@P0034:					; CODE XREF: sub_5589+16Dp
		mov	b, h
		mov	c, l
; End of function @P0034


; ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ S U B	R O U T	I N E ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ


@P0035:					; CODE XREF: sub_5589+43Ap
		lxi	h, 0		; @P0035()
		mvi	a, 10h

loc_5D6F:				; CODE XREF: @P0035+Ej
		dad	h
		xchg
		dad	h
		xchg
		jnc	loc_5D77
		dad	b

loc_5D77:				; CODE XREF: @P0035+9j
		dcr	a
		jnz	loc_5D6F
		ret
; End of function @P0035

; ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД
		.db 0, 0, 0, 0,	0, 0, 0, 0, 0, 0, 0, 0,	0, 0, 0, 0, 0
		.db 0, 0, 0, 0,	0
word_5D92:	.dw 0			; DATA XREF: sub_501C+6o sub_501C+1Cw	...
word_5D94:	.block 2		; DATA XREF: sub_501C+22w PUTRECORD+Ar ...
byte_5D96:	.block 1		; DATA XREF: sub_501C+16w
					; PUTRECORD+13o ...
		.block 1
byte_5D98:	.block 1		; DATA XREF: sub_50D7+17w
byte_5D99:	.block 3		; DATA XREF: sub_501C+1Fo
byte_5D9C:	.block 1		; DATA XREF: sub_5589+C2o
					; sub_5589+210o ...
		.block 400h
byte_619D:	.block 1		; DATA XREF: sub_5589+DDo sub_5589+F3o ...
byte_619E:	.block 400h		; DATA XREF: sub_5589+207o
byte_659E:	.block 802h		; DATA XREF: sub_5589+8Eo sub_5589+98o ...
word_6DA0:	.block 2		; DATA XREF: sub_545A+45r sub_5589+Fr	...
?sub_501C:	.block 1		; arg1b	; DATA XREF: sub_501Co
					; sub_501C+13r
?PUTRECORD:	.block 2		; arg1w	; DATA XREF: PUTRECORD+Er
					; PUTRECORD+25r ...
		.block 2		; arg2w
word_6DA7:	.block 2		; DATA XREF: PUTRECORD+3Cw
					; PUTRECORD+42o ...
word_6DA9:	.block 2		; DATA XREF: PUTRECORD+29w
					; PUTRECORD+3Fo
?sub_50C1:	.block 2		; arg1w	; DATA XREF: sub_50C1+6r
					; sub_50C1+Br ...
word_6DAD:	.block 2		; DATA XREF: sub_50D7+Bw sub_50D7+13r	...
word_6DAF:	.block 2		; DATA XREF: sub_50D7+2Aw sub_50D7+30o ...
?sub_5206:	.block 1		; arg1b	; DATA XREF: sub_5206+Do
					; sub_5206+16o	...
		.block 2		; arg2w
		.block 1		; arg3b
byte_6DB5:	.block 1		; DATA XREF: sub_5149+14o sub_5149+1Bo ...
byte_6DB6:	.block 1		; DATA XREF: sub_52AAo	sub_52AA+7o ...
word_6DB7:	.block 2		; DATA XREF: sub_52AA+11w sub_52AA+16o ...
word_6DB9:	.block 2		; DATA XREF: sub_52AA+77w
word_6DBB:	.block 2		; DATA XREF: sub_52AA+64w sub_52AA+71o ...
word_6DBD:	.block 2		; DATA XREF: sub_53A3+Fw sub_53A3+17o	...
word_6DBF:	.block 2		; DATA XREF: sub_53A3+38w sub_53A3+3Br ...
word_6DC1:	.block 2		; DATA XREF: sub_53A3+4Cw
byte_6DC3:	.block 1		; DATA XREF: sub_545A+27o sub_545A+2Fo ...
word_6DC4:	.block 2		; DATA XREF: sub_545A+83o sub_545A+90r ...
word_6DC6:	.block 2		; DATA XREF: sub_545A+61w sub_545A+75w ...
word_6DC8:	.block 2		; DATA XREF: sub_5535+14w sub_5535+1Bo ...
byte_6DCA:	.block 1		; DATA XREF: sub_5589o	sub_5589+9r ...
word_6DCB:	.block 2		; DATA XREF: sub_5589+F9r
					; sub_5589+199o ...
word_6DCD:	.block 2		; DATA XREF: sub_5589+CBw sub_5589+D1o ...
word_6DCF:	.block 2		; DATA XREF: sub_5589+458w
					; sub_5589+52Fo ...
word_6DD1:	.block 2		; DATA XREF: sub_5589+45Ew
					; sub_5589+466o ...
word_6DD3:	.block 2		; DATA XREF: sub_5589+69w sub_5589+78w ...
word_6DD5:	.block 2		; DATA XREF: sub_5589+BAw sub_5589+BDr ...
word_6DD7:	.block 2		; DATA XREF: sub_5589+190o
					; sub_5589+244w ...
word_6DD9:	.block 2		; DATA XREF: sub_5589+FCw
					; sub_5589+1A2o ...
word_6DDB:	.block 2		; DATA XREF: sub_5589+106w
					; sub_5589+1ADo
word_6DDD:	.block 2		; DATA XREF: sub_5589+1CBw
					; sub_5589+1D8r ...
byte_6DDF:	.block 1		; DATA XREF: sub_5589+179o
					; sub_5589+226r ...
byte_6DE0:	.block 1		; DATA XREF: sub_5589+15Co
					; sub_5589+171r ...
byte_6DE1:	.block 1		; DATA XREF: sub_5589+134w
					; sub_5589+165r ...
byte_6DE2:	.block 1		; DATA XREF: sub_5589+13Co
					; sub_5589+145r ...
word_6DE3:	.block 2		; DATA XREF: sub_5589+214w
					; sub_5589+26Cr ...
byte_6DE5:	.block 1		; DATA XREF: sub_5AEA+Bo sub_5AEA+45r
word_6DE6:	.block 2		; DATA XREF: sub_5AEA+1Eo sub_5AEA+3Ar
byte_6DE8:	.block 1		; DATA XREF: sub_5B46+25o sub_5B46+2Co ...
word_6DE9:	.block 2		; DATA XREF: PASS2+30w	PASS2+35o ...
		.block 2
byte_6DED:	.block 2627h		; DATA XREF: PASS2o
; end of 'ROM'


		.end
