#ifndef VERSION_H
// Autogenerated version information
#define GITVERSION_STR "0.1.3"
#define FILEVERSION_STR "0.1.3.0\0"
#define FILEVERSION_RC 0,1,3,0
#define GIT_PRIVATE 0
#define GIT_PATCHED 0
#define GIT_PRERELEASE 0
#define COMMITDATE_STR "2020-04-30"
#define COPYRIGHT_STR "(C) 2020  Mark Ogden"
#endif
