#ifndef VERSION_H
// Autogenerated version information
#define GITVERSION_STR "0.1.1"
#define FILEVERSION_STR "0.1.1.0"
#define FILEVERSION_RC 0,1,1,0
#define COMMITDATE_STR "2020-04-28"
#define COPYRIGHT_STR "(C) 2020  Mark Ogden"
#endif
