cd common & ..\..\nmake vclean
cd ..\plm & ..\..\nmake vclean
cd ..\plm0 & ..\..\nmake vclean
cd ..\plm1 & ..\..\nmake vclean
cd ..\plm2 & ..\..\nmake vclean
cd ..\plm3 & ..\..\nmake vclean
cd ..\plm4 & ..\..\nmake vclean
cd ..\plm5 & ..\..\nmake vclean
cd ..\plm6 & ..\..\nmake vclean
cd ..\link80 & ..\..\nmake gitprep
cd ..\loc80 & ..\..\nmake gitprep
cd ..\asm80 & ..\..\nmake gitprep
cd ..\lib80 & ..\..\nmake gitprep
cd ..\isis41 & ..\..\nmake clean
cd ..\isis.cli & ..\..\nmake gitprep
cd ..\isist0 & ..\..\nmake clean
cd ..\ixref & ..\..\nmake gitprep
cd ..\plm80lib & ..\..\nmake gitprep
cd ..\systemlib & ..\..\nmake gitprep
cd ..
