cd common & ..\..\make distclean
cd ..\plm & ..\..\make distclean
cd ..\plm0 & ..\..\make distclean
cd ..\plm1 & ..\..\make distclean
cd ..\plm2 & ..\..\make distclean
cd ..\plm3 & ..\..\make distclean
cd ..\plm4 & ..\..\make distclean
cd ..\plm5 & ..\..\make distclean
cd ..\plm6 & ..\..\make distclean
cd ..\link_3.0 & ..\..\make distclean
cd ..\locate_3.0 & ..\..\make distclean
cd ..\asm80_4.1 & ..\..\make distclean
cd ..\lib_2.1 & ..\..\make distclean
cd ..\isis34 & ..\..\make distclean
cd ..\isis34.t0 & ..\..\make distclean
cd ..\isis41 & ..\..\make distclean
cd ..\isis41.cli & ..\..\make distclean
cd ..\isis41.t0 & ..\..\make distclean
cd ..\ixref_1.2 & ..\..\make distclean
cd ..\ixref_1.3 & ..\..\make distclean
cd ..\plm80lib & ..\..\make distclean
cd ..\systemlib & ..\..\make distclean
cd ..\isis43 & ..\..\make distclean
cd ..\isis43.cli & ..\..\make distclean
cd ..\isis43.t0 & ..\..\make distclean
cd ..\isis43.ov0 & ..\..\make distclean
cd ..\kermit & ..\..\make distclean
cd ..\tex & ..\..\make distclean
cd ..
