pushd asm80_4.1 & make distclean & popd
pushd binobj_3.4 & make distclean & popd
pushd help_1.1 & make distclean & popd
pushd hexobj_4.3 & make distclean & popd
pushd isis.cli_4.1 & make distclean & popd
pushd isis.cli_4.3 & make distclean & popd
pushd isis.ov0_4.3 & make distclean & popd
pushd isis.t0_2.2 & make distclean & popd
pushd isis.t0_3.4 & make distclean & popd
pushd isis.t0_4.0 & make distclean & popd
pushd isis.t0_4.1 & make distclean & popd
pushd isis.t0_4.3 & make distclean & popd
pushd isis.t0_4.3w & make distclean & popd
pushd isisUtil_4.3 & make distclean & popd
pushd isis_3.4 & make distclean & popd
pushd isis_4.0 & make distclean & popd
pushd isis_4.1 & make distclean & popd
pushd isis_4.3 & make distclean & popd
pushd isis_4.3w & make distclean & popd
pushd ixref_1.2 & make distclean & popd
pushd ixref_1.3 & make distclean & popd
pushd kermit & make distclean & popd
pushd lib_2.1 & make distclean & popd
pushd link_3.0 & make distclean & popd
pushd locate_3.0 & make distclean & popd
pushd objhex_2.2n & make distclean & popd
pushd objhex_4.3 & make distclean & popd
pushd plm80.lib & make distclean & popd
pushd plm_4.0 & make distclean & popd
pushd submit_4.3 & make distclean & popd
pushd system.lib_4.0 & make distclean & popd
pushd tex & make distclean & popd
pushd toolbox_1.0 & make distclean & popd
pushd toolbox_2.0 & make distclean & popd
pushd vers_4.3 & make distclean & popd
