$TITLE('CP/M BOOTSTRAP FOR SBC-80/24')
; BIOS LOADER (ROM RESIDENT) PROGRAM
; TO RUN CP/M-80 ON SBC-80/24.
;
ROMCOD	EQU  200H
BOOT	EQU  0F200H
BOOLEN	EQU  0E00H
;
        ORG  0
        DI
        LXI  D,ROMCOD  ; POINT TO WERE MONITOR SITS IN ROM
        LXI  H,BOOT    ; POINT TO START OF WHERE IT GOES
        LXI  B, BOOLEN ; LENGTH OF MOVE
MOVEIT:
        LDAX D         ; GET SOURCE STRING BYTE
        MOV  M,A       ; STORE AT DESTINATION
        INX  D         ; BUMP SOURCE POINTER
        INX  H         ; BUMP DESTINATION POINTER
        DCX  B         ; DECREMENT COUNT
        MOV  A,C
        ORA  B         ; TEST COUNT = 0
        JNZ  MOVEIT    ; LOOP IF NOT DONE

        JMP  BOOT      ; JUMP TO DISK BOOTSTRAP

        END
