//
// +-------------------------------------------------------------------------+
// |   This file has been generated by The Interactive Disassembler (IDA)    |
// |           Copyright (c) 2017 Hex-Rays, <support@hex-rays.com>           |
// |                      License info: 48-B9BB-7C04-99                      |
// |                      Mark Ogden, Personal license                       |
// +-------------------------------------------------------------------------+
//

// DUMP OF RANGE 466F..4697

#define UNLOADED_FILE   1
#include <idc.idc>

static main(void)
{
        Patches();              // info about patches bytes
        SegRegs();              // segment register values
        Bytes();                // individual bytes (code,data)
        Functions();            // function definitions
}

//------------------------------------------------------------------------
// Information about bytes

static Bytes_0(void) {
        auto x;
#define id x

}

static Functions_0(void) {

}

//------------------------------------------------------------------------
// Information about functions

static Functions(void) {

	Functions_0();
}

//------------------------------------------------------------------------
// Information about segment registers

static SegRegs(void) {
}

//------------------------------------------------------------------------
// Information about all patched bytes:

static Patches(void) {
}

//------------------------------------------------------------------------
// Call all byte feature functions:

static Bytes(void) {
	Bytes_0();
        end_type_updating(UTP_STRUCT);
}

// End of file.
